name: Dependabot Auto-Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    needs: auto-approve
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        if: github.actor == 'dependabot[bot]'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
